config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :posts do
    post 'create_comment', on: :collection
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :name, presence: true
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  attribute :user_type, :integer, default: 0

  enum user_type: [:user,:manager,:admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[ show edit update destroy create_comment ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comment = @post.comments.new unless @post.blank?
    @comments = Comment.where(post_id: @post).order("created_at ASC")
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_comment
    @post = Post.find_by_id params[:comment][:post_id]
    @comment = @post.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_url(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find_by_id(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :name)
    end

  def comment_params
    params.require(:comment).permit(:name, :body, :post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog-Nucleus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

  </head>


  <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-purple">
    <%= render 'shared/header' %>
  </nav>

  <body class="">
    <%= yield %>
  </body>


  <nav class="navbar navbar-expand-lg  fixed-bottom navbar-dark bg-purple">
    <%= render 'shared/footer' %>
  </nav>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container mt-5 col-lg-9 col-md-10 col-sm-12 col-xs-12">

  <h1 class="mb-5 shadow-none p-3 mb-5 bg-light rounded">Noticias</h1>
  <div class="shadow-none p-3 mb-5 bg-light rounded d-flex justify-content-center">
    <div class="d-flex flex-column mb-3 col-lg-9 col-md-10 col-sm-12 col-xs-12">
      <% @posts.each do |post| %>
        <div class="card mb-3 shadow-sm">
          <div class="card-body shadow-sm">
            <h4 class="card-title text-center"><%= post.title %></h4>
          </div>
          <div class="comment-widgets scrollable">
            <div class="d-flex flex-row comment-row mt-0">
              <div class="p-2">
                <img
                  src="../assets/images/users/1.jpg"
                  alt="user"
                  width="50"
                  class="rounded-circle"
                  />
              </div>
              <div class="comment-text w-100">
                <h6 class="font-medium">Autor: <%= post.name %></h6>
                <span class="mb-3 d-block"><%= post.body %></span>
                <div class="comment-footer">
                  <span class="text-muted float-end"><%= post.created_at %></span>
                  <%= link_to 'Show', post, class:"btn btn-success btn-sm text-white" %>
                  <% if current_user.admin? %>
                  <%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary btn-sm text-white"  %>
                  <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm text-white" %>
                    <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/partials/_comments.html.erb
<% if @comments.count > 0
     @comments.each do |comment|
%>
<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 mb-3">

  <div class="card">
    <div class="comment-widgets scrollable">
      <!-- Comment Row -->
      <div class="d-flex flex-row comment-row mt-0">
        <div class="p-2">
          <img
            src="https://appnucleus.com.br/assets/Logo%20Verde-239c4f3db34e025da6e2d6c564491f63891e14178e1fa0231c32e2c9aa67e50f.png"
            alt="user"
            width="50"
            class="rounded-circle"
            />
        </div>

        <div class="comment-text w-100">
        <h6 class="font-medium"><%= comment.name %></h6>
          <span class="mb-3 d-block"><%= comment&.body %></span>
          <div class="comment-footer">
            <span class="text-muted float-end"><%= comment&.created_at %></span>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
            <% end end %>

app/views/posts/partials/_new_comment.html.erb
<div class="mt-5">
  <%= form_with(model: @comment, url: create_comment_posts_path, method: "post") do |form| %>
    <% if @comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="">
      <%= form.hidden_field :post_id, value: @post.id %>
      <div class="card">
        <div class="comment-widgets scrollable">
          <!-- Comment Row -->
          <div class="d-flex flex-row comment-row mt-0">


            <div class="comment-text w-100">

              <div class="d-flex flex-column align-items-start">
                <div class="d-flex">
                  <img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40">
                  <%= form.text_field :name , class: "form-control ml-1 shadow-none name_area" %>
                </div>
                <%= form.text_area :body , class: "form-control ml-1 shadow-none textarea" %>
              </div>

                <div class="mt-2 text-right">
                  <%= form.submit "Comentar" , class: "btn btn-primary btn-sm shadow-none"%>
                </div>

            </div>
          </div>
        </div>
      </div>
    </div>


  <% end %>

</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container mt-5 col-lg-9 col-md-10 col-sm-12 col-xs-12">
  <h1 class="mb-5 shadow-none p-3 mb-5 bg-light rounded"><%= link_to 'Voltar', posts_path, class: "btn btn-primary btn-lg text-white" %></h1>
  <div class="shadow-none p-3 mb-5 bg-light rounded d-flex row justify-content-center">
    <div class="d-flex flex-column mb-3 col-lg-9 col-md-10 col-sm-12 col-xs-12">
      <div class="card mb-3 shadow-sm">
        <div class="card-body shadow-sm">
          <h4 class="card-title text-center"> <%= @post.title %></h4>
        </div>
        <div class="comment-widgets scrollable">
          <div class="d-flex flex-row comment-row mt-0">
            <div class="p-2">
              <img
                src="../assets/images/users/1.jpg"
                alt="user"
                width="50"
                class="rounded-circle"
                />
            </div>
            <div class="comment-text w-100">
              <h6 class="font-medium">Autor:  <%= @post.name %> </h6>
              <span class="mb-3 d-block">  <%= @post.body %></span>
              <div class="comment-footer">
                <span class="text-muted float-end"><%= @post.created_at %></span>
                <%#= link_to 'Show', post, class:"btn btn-success btn-sm text-white" %>

                <% if current_user.admin? %>
                  <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary btn-sm text-white"  %>
                  <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm text-white" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="d-flex row flex-column col-lg-12 col-md-6 col-sm-12 col-xs-12 mb-3">
      <%= render 'posts/partials/comments' %>
    </div>


      <%= render 'posts/partials/new_comment' %>


      </div>

</div>

app/views/shared/_footer.html.erb
<div class="container-fluid px-30">
  <a class="navbar-brand" href="#">
    <img src="https://appnucleus.com.br/assets/Logo%20Verde-239c4f3db34e025da6e2d6c564491f63891e14178e1fa0231c32e2c9aa67e50f.png" alt="" width="30" height="24" class="d-inline-block align-text-top">
    NucleusBlog
  </a>
  <h6 class="text-white">Copyright Nucleus 2022 - Todos os direitos reservados</h6>
</div>

app/views/shared/_header.html.erb
<div class="container-fluid px-30">
  <a class="navbar-brand" href="#">
    <img src="https://appnucleus.com.br/assets/Logo%20Verde-239c4f3db34e025da6e2d6c564491f63891e14178e1fa0231c32e2c9aa67e50f.png" alt="" width="30" height="24" class="d-inline-block align-text-top">
    NucleusBlog
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        <a class="nav-link" href="#">Blog</a>
        <a class="nav-link" href="#">Contato</a>
      </div>
    </div>
  <form class="d-flex" role="search">
    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    <button class="btn btn-outline-light" type="submit">Search</button>
  </form>
  <div>
    <% if current_user %>
      <nav class=" ">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Editar</a></li>
                <li><a class="dropdown-item" href="#">Meus Posts</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    <% else %>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <%= link_to "Login", user_session_path, class: "nav-link" %>
          <%= link_to "Registre-se" , user_registration_path, class: "nav-link" %>
        </div>
    <% end %>
    </div>
  </div>
</div>